# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: arestorosra
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: lambda-crud
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lmabda-crud-node-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role: arn:aws:iam::590704828383:role/LabRole
    deploymentRole: arn:aws:iam::590704828383:role/LabRole
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:590704828383:table/TaskTable

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  addTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  listTasks:
    handler: src/listTask.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH